os: osx
language: java
jdk:
  - openjdk8
#build stage
jobs:
  include:
    - stage: unit_test
      script: sh ./scripts/unit_test.sh
    - stage: packaging
      script: ./deploy
      on:
        branch: master