os: osx
language: java
services:
    - docker
jdk:
  - openjdk8
#build stage
jobs:
  include:
    - stage: unit_test
      script: sh ./scripts/unit_test.sh
      on:
        branch: master
    - stage: unit_test
      script: sh ./scripts/docker_publish.sh
      on:
        branch: master   
